#!/bin/bash

ln -s /etc/trino /usr/local/trino/etc

set +e
grep -s -q 'node.id' /usr/local/trino/etc/node.properties
NODE_ID_EXISTS=$?
set -e

NODE_ID=""
if [[ ${NODE_ID_EXISTS} != 0 ]] ; then
    NODE_ID="-Dnode.id=${HOSTNAME}"
fi

exec /usr/local/trino/bin/launcher run ${NODE_ID} "$@"